/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthButton: typeof import('./../src/views/auth/components/AuthButton.vue')['default']
    Compute: typeof import('./../src/components/Compute.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ExampleCssClamp: typeof import('./../src/views/example-view/components/ExampleCss/ExampleCssClamp.vue')['default']
    ExampleCssContainerQuery: typeof import('./../src/views/example-view/components/ExampleCss/ExampleCssContainerQuery.vue')['default']
    ExampleCssContainerStyle: typeof import('./../src/views/example-view/components/ExampleCss/ExampleCssContainerStyle.vue')['default']
    ExampleCssFirstLetter: typeof import('./../src/views/example-view/components/ExampleCss/ExampleCssFirstLetter.vue')['default']
    ExampleCssGradient: typeof import('./../src/views/example-view/components/ExampleCss/ExampleCssGradient.vue')['default']
    ExampleCssNestingBind: typeof import('./../src/views/example-view/components/ExampleCss/ExampleCssNestingBind.vue')['default']
    ExampleCssScroll: typeof import('./../src/views/example-view/components/ExampleCss/ExampleCssScroll.vue')['default']
    ExampleCssSelectElement: typeof import('./../src/views/example-view/components/ExampleCss/ExampleCssSelectElement.vue')['default']
    ExampleCssText: typeof import('./../src/views/example-view/components/ExampleCss/ExampleCssText.vue')['default']
    ExampleCssViewport: typeof import('./../src/views/example-view/components/ExampleCss/ExampleCssViewport.vue')['default']
    ExampleViewComponent: typeof import('./../src/views/example-view/components/ExampleViewComponent.vue')['default']
    FF: typeof import('./../src/components/FF.vue')['default']
    IconCar: typeof import('~icons/icon/car')['default']
    IconCart: typeof import('~icons/icon/cart')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Text: typeof import('./../src/views/example-view/components/ExampleCss/Text.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
