/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppAvatar: typeof import('./../src/components/AppAvatar.vue')['default']
    AppLogo: typeof import('./../src/components/AppLogo.vue')['default']
    Badge: typeof import('./../src/components/Badge.vue')['default']
    BurgerMenu: typeof import('./../src/components/icons/BurgerMenu.vue')['default']
    CloseCross: typeof import('./../src/components/icons/CloseCross.vue')['default']
    ContactItem: typeof import('./../src/components/ContactItem.vue')['default']
    Dots: typeof import('./../src/components/icons/Dots.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Gear: typeof import('./../src/components/icons/Gear.vue')['default']
    Header: typeof import('./../src/components/Header.vue')['default']
    LeftSidebar: typeof import('./../src/components/LeftSidebar.vue')['default']
    Logo: typeof import('./../src/components/icons/Logo.vue')['default']
    LogOutButton: typeof import('./../src/components/LogOutButton.vue')['default']
    MagnifyingGlass: typeof import('./../src/components/icons/MagnifyingGlass.vue')['default']
    Message: typeof import('./../src/views/chat/components/Message.vue')['default']
    MessageForm: typeof import('./../src/views/chat/components/MessageForm.vue')['default']
    RightSidebar: typeof import('./../src/components/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
